config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
  

  namespace :admin do 
    root "categories#index"
    resources :categories
    resources :users
  end

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy]
    member do 
      post :collect
      post :uncollect
    end 
    collection do 
      get :feeds
    end
  end
   
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end



  resources :friend_requests2s
  resources :friendship2s
  resources :drafts
  resources :categories
  resources :users, only: [:show, :edit, :update, :posted_articles, :posted_drafts] do
    member do
      get :posted_articles
      get :posted_drafts
      get :posted_comments
      get :collected_articles
      get :friends
    end
    get '/friend_requests2s', to: 'friend_requests2s#index'
    get '/friends', to: 'friendship2s#index'
  end


end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # has_many :article_categories
  # has_many :articles, through: :article_categories
  has_and_belongs_to_many :articles, dependent: :destroy

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_category, only: [:update, :destroy]
  
  def index
    @categories = Category.all
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "category was successfully updated"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not Allow"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    if current_user
      @q = @category.articles.readable_articles(current_user).ransack(params[:q])
    else  
      @q = @category.articles.where(authority: "all").ransack(params[:q])
    end
    @article = @q.result.includes(:comments).page(params[:page]).per(10)
  end

  def index
    @categories = Category.all
    
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="navbar-collapse navbar-collapse_ collapse">
    <ul class="nav navbar-nav sf-menu clearfix">
      <li class="active"><%= link_to 'Categories List', admin_categories_path %><em></em></li>
      <li ><%= link_to 'User List', admin_users_path %><em></em></li>
    </ul>
  </div>

  <br>
  <div class="form-inline" >
    <!-- [:admin, @category] :admin 是 namespace 的路徑。 -->
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
      <% if @category.errors.any? %>
        <%= @category.errors.full_messages.to_sentence %>
      <% end %>
    <% end %>
  </div>
  <br>

  <div class="row">

    <div class="col-md-8">
  
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Category Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <%= link_to 'Edit', admin_categories_path(id: category.id), class: "btn btn-xs btn-primary" %>  
              <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-primary"%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>