config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
  

  namespace :admin do 
    root "categories#index"
    resources :categories
    resources :users
  end

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy]
    member do 
      post :collect
      post :uncollect
    end 
    collection do 
      get :feeds
    end
  end
   
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end



  resources :friend_requests2s
  resources :friendship2s
  resources :drafts
  resources :categories
  resources :users, only: [:show, :edit, :update, :posted_articles, :posted_drafts] do
    member do
      get :posted_articles
      get :posted_drafts
      get :posted_comments
      get :collected_articles
      get :friends
    end
    get '/friend_requests2s', to: 'friend_requests2s#index'
    get '/friends', to: 'friendship2s#index'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :content

  belongs_to :user

  has_many :comments
    
  # has_many :article_categories
  # has_many :categories, through: :article_categories
  has_and_belongs_to_many :categories

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  mount_uploader :image, ImageUploader

  def published?
    published_at?
  end

  def is_collected?(user)
    self.collected_users.include?(user)
  end

  def self.readable_articles(user)
    Article.where(authority: "friend", user: user.friends).or( where(authority: "all")).or(where(authority: "myself", user: user)).or(where( user: user))
  end

  def check_authority_for?(user)
    Article.readable_articles(user).include?(self)
  end

  is_impressionable :counter_cache => true, :column_name => :views_count
  
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  self.table_name = "articles_categories"
  
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # has_many :article_categories
  # has_many :articles, through: :article_categories
  has_and_belongs_to_many :articles, dependent: :destroy

end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: :comments_count
  belongs_to :article, counter_cache: :comments_count
end

app/models/friend_requests2.rb
class FriendRequests2 < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  validate :not_self
  validate :not_friends
  validate :not_pending

  def accept_friend
    user.friends << friend
    friend.friends << user
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end
end

app/models/friendship2.rb
class Friendship2 < ApplicationRecord
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  validate :not_self

  private

  def create_inverse_relationship
    friend.friendship2s.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship2 = friend.friendship2s.find_by(friend: user)
    friendship2.destroy if friendship2
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_articles, through: :collects, source: :article

  has_many :friend_requests2s, dependent: :destroy
  has_many :pending_friends, through: :friend_requests2s, source: :friend

  has_many :friendship2s, dependent: :destroy
  has_many :friends, through: :friendship2s

  mount_uploader :avatar, AvatarUploader

  ROLE_STATUS = [
    ["Admin", :admin],
    ["Normal", :normal]
  ]

  def admin?
    self.role == "admin"
  end

  def remove_friend(friend)
    friends.destroy(friend)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def edit
  end

  def update 
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "User Role Updated"
    else
      flash.now[:alert] = @order.errors.full_messages.to_sentence
      render "admin/users/edit"  
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not Allow"
      redirect_to root_path
    end
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])
      sign_in(user, store: false) if user
    end
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :posted_articles, :posted_drafts, :posted_comments, :collected_articles, :friends]

  def show
    @posted_articles = @user.articles
  end

  def edit
    unless @user == current_user
      redirect_to posted_articles_user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to posted_articles_user_path(@user)
  end

  def posted_articles
    @posted_articles = @user.articles
  end

  def posted_drafts
    @posted_articles = @user.articles
  end

  def posted_comments
    @posted_comments = @user.comments.page(params[:page]).per(5)
  end

  def collected_articles
    @collected_articles = @user.collected_articles
  end

  def friends
    @received = FriendRequests2.where(friend: current_user)
    @sent = current_user.friend_requests2s
    @friends = @user.friends
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendship2s_helper.rb
module Friendship2sHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">


  <div class="navbar-collapse navbar-collapse_ collapse">
    <ul class="nav navbar-nav sf-menu clearfix">
      <li ><%= link_to 'Categories List', admin_categories_path %><em></em></li>
      <li class="active"><%= link_to 'User List', admin_users_path %><em></em></li>
    </ul>
  </div>



  <div class="row">

    <div class="col-md-8">
  
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td>
              <%= form_for [:admin, user] do |f| %>
                <p>
                  <%= f.select :role, User::ROLE_STATUS %>
                  <%= f.submit %>
                </p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/users/collected_articles.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_nav" %>
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-striped">
        <tbody>
          <% @collected_articles.each do |article|%>
            <tr>
              <td><%= article.title %> <br></td>  
              <td>
                <%= render partial: "shared/user_collect", locals: { article: article } %>
              </td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Edit Profile</h3>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, class: "form-control" %>
        </div>
         <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-primary" %>
          <%= link_to "Cancel", posted_articles_user_path(@user),class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/friends.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_nav" %>
    <div class="col-md-10 col-md-offset-1 requested_friend_list">
      <div class="friend-page-header">
        <h3>Waiting for response</h3>
      </div>
      <% @sent.each do |request| %>
        <div class="col-md-2 col-sm-3 col-xs-5 text-center user-item requested_friend">
          <!-- <img src="http://via.placeholder.com/100x100"> -->
          <%= image_tag request.friend.avatar, width: "100%", class: "img-responsive img-rounded" if request.friend.avatar? %>
          <h5><%= request.friend.name %></h5>
        </div>
      <% end %>
    </div>
    <div class="col-md-10 col-md-offset-1 received_friend_list">
      <% @received.each do |request| %>
        <div class="col-md-2 col-sm-3 col-xs-5 text-center user-item received_friend">
          <!-- <img src="http://via.placeholder.com/100x100"> -->
          <%= image_tag request.user.avatar, width: "100%", class: "img-responsive img-rounded" if request.user.avatar? %>
          <h5><%= request.user.name %></h5>
          <div class="btn-group">
            <%= link_to 'Accept', friend_requests2_path(request.id), method: :patch, class: 'btn btn-info btn-raised btn-sm' %> <br>
            <%= link_to 'Ignore', friend_requests2_path(request.id), method: :delete, class: 'btn btn-danger btn-simple btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>    

    <div class="col-md-10 col-md-offset-1 friend_list ">
      <% @friends.each do |friend| %>
        <div class="col-md-2 col-sm-3 col-xs-5 text-center user-item friend">
          <!-- <img src="http://via.placeholder.com/100x100"> -->
          <%= image_tag friend.avatar, width: "100%", class: "img-responsive img-rounded" if friend.avatar? %>
          <h5><%= friend.name %></h5>
          <% if current_user.friends.include?(friend) %>
          <%= link_to "Remove friend", friendship2_path(friend), method: :delete, class: "btn btn-danger btn-raised" %>
        <% end %>
        </div>
      <% end %>
    </div>      
  </div>
</div>

app/views/users/posted_articles.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_nav" %>

    <div class="col-md-10 col-md-offset-1">
      <table class="table table-striped">
        <tbody>
          <% @posted_articles.each do |article|%>
            <% if article.published? %>
            <tr>
              <td><%= article.title %></td>
              <td>
                <% if article.published? %>
                  <span>Published</span>
                <% else %>
                  <span >Draft</span>
                <% end %>
              </td>
            <td><%= article.updated_at.strftime('%Y-%m-%d') %></td>
            <td>
              <% if current_user == article.user %>
                <i>
                  <%= link_to '', edit_article_path(article), class: "fas fa-pen-square" %>    
                </i>
                <i> 
                  <%= link_to '', article_path(article), method: :delete, data: {confirm:"Are you sure?"}, class: "far fa-trash-alt" %>
                </i>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Post', new_article_path, class: "btn btn-md btn-primary" %>
  </div>
</div>

app/views/users/posted_comments.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_nav" %>
    <div class="col-md-10 col-md-offset-1">
      <div id="comment">
        <% @posted_comments.each do |comment| %>
        <div class="col-md-12 profile_comment " id="<%= comment.id %>" >
          <div class="col-md-12">
            <p>
              Post Title: <%= comment.article.title %>
            </p>
          </div> 
          <div class="col-md-6">
            <p class="tweets">
              <%= comment.content %>
            </p>
          </div>
          <div class="col-md-4">
            <div class="profile_comment_icon">
              <%= link_to '', edit_article_comment_path(id: comment.id, article_id: comment.article.id), class: "fas fa-pen-square" %>
              <%= link_to '', article_comment_path(id: comment.id, article_id: comment.article.id), method: :delete, data: {confirm:"Are you sure?"}, class: "far fa-trash-alt" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>  
      <div class="clearfix"></div>
      <div class="page">
        <%= paginate @posted_comments %>
      </div>
    </div>
  </div>
</div>

app/views/users/posted_drafts.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/user_nav" %>
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-striped">
        <tbody>
          <% @posted_articles.each do |article|%>
            <% unless article.published? %>
            <tr>
              <td><%= article.title %> <br></td>
              <td>
                <% if article.published? %>
                  <span>Published</span>
                <% else %>
                  <span >Draft</span>
                <% end %>
              </td>
              <td><%= article.updated_at.strftime('%Y-%m-%d') %></td>
              <td>
                <% if current_user == article.user %>
                  <i>
                    <%= link_to '', edit_article_path(article), class: "fas fa-pen-square" %></i>
                  <i> 
                    <%= link_to '', article_path(article), method: :delete, data: {confirm:"Are you sure?"}, class: "far fa-trash-alt" %>
                  </i>
                <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="page-header">
        <div class="col-md-3 col-sm-4">
          <div class="text-center">
           <!--  <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded"> -->
          <%= image_tag user.avatar, width: "100%", class: "img-responsive img-rounded" if user.avatar? %>
          </div>
           <div class="pull-left">
          <h2><%= @user.name %></h2>
        </div>
        </div>
        <div class="col-md-9 col-sm-8">
          <div class="user_intro">
              <%= simple_format @user.intro %>
          </div>
          <div class="user_edit">
            <% if @user == current_user %>
              <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-md btn-primary" %>
            <% end %>
            <%unless @user == current_user %>
              <%= render partial: "shared/user_friend", locals: {user: @user} %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
      <br>
      <div class="col-md-10">
        <ul class="nav nav-tabs">
          <li class="active"><%= link_to 'My Post', posted_articles_user_path(@user), method: :get %> </li>
          <li><a href="#">My Comment</a></li>
          <li><a href="#">My Collect</a></li>
          <li><%= link_to 'My Draft', posted_drafts_user_path(@user), method: :get %> </li>
          <li><a href="#">My Friend</a></li>
        </ul>
      </div>
      <table class="table table-striped">
        <tbody>
          <% @posted_articles.each do |article|%>
            <% if article.published? %>
            <tr>
              <td><%= article.title %> <br></td>
              <td>
                <% if article.published? %>
                  <span>Article</span>
                <% else %>
                  <span >Draft</span>
                <% end %>
              </td>
            <td><%= article.updated_at %></td>
            <td>
              <% if current_user == article.user %>
                <i>
                  <%= link_to '', edit_article_path(article), class: "fas fa-pen-square" %></i>
                <i> 
                  <%= link_to '', article_path(article), method: :delete, data: {confirm:"Are you sure?"}, class: "far fa-trash-alt" %>
                </i>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Post', new_article_path, class: "btn btn-md btn-primary" %>
  </div>
</div>