config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
  

  namespace :admin do 
    root "categories#index"
    resources :categories
    resources :users
  end

  resources :articles do
    resources :comments, only: [:create, :edit, :update, :destroy]
    member do 
      post :collect
      post :uncollect
    end 
    collection do 
      get :feeds
    end
  end
   
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :articles, only: [:index, :create, :show, :update, :destroy]
    end
  end



  resources :friend_requests2s
  resources :friendship2s
  resources :drafts
  resources :categories
  resources :users, only: [:show, :edit, :update, :posted_articles, :posted_drafts] do
    member do
      get :posted_articles
      get :posted_drafts
      get :posted_comments
      get :collected_articles
      get :friends
    end
    get '/friend_requests2s', to: 'friend_requests2s#index'
    get '/friends', to: 'friendship2s#index'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :content

  belongs_to :user

  has_many :comments
    
  # has_many :article_categories
  # has_many :categories, through: :article_categories
  has_and_belongs_to_many :categories

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user

  mount_uploader :image, ImageUploader

  def published?
    published_at?
  end

  def is_collected?(user)
    self.collected_users.include?(user)
  end

  def self.readable_articles(user)
    Article.where(authority: "friend", user: user.friends).or( where(authority: "all")).or(where(authority: "myself", user: user)).or(where( user: user))
  end

  def check_authority_for?(user)
    Article.readable_articles(user).include?(self)
  end

  is_impressionable :counter_cache => true, :column_name => :views_count
  
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  self.table_name = "articles_categories"
  
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # has_many :article_categories
  # has_many :articles, through: :article_categories
  has_and_belongs_to_many :articles, dependent: :destroy

end

app/models/collect.rb
class Collect < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: :comments_count
  belongs_to :article, counter_cache: :comments_count
end

app/models/friend_requests2.rb
class FriendRequests2 < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  validate :not_self
  validate :not_friends
  validate :not_pending

  def accept_friend
    user.friends << friend
    friend.friends << user
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end
end

app/models/friendship2.rb
class Friendship2 < ApplicationRecord
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  validate :not_self

  private

  def create_inverse_relationship
    friend.friendship2s.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship2 = friend.friendship2s.find_by(friend: user)
    friendship2.destroy if friendship2
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments, dependent: :destroy

  has_many :collects, dependent: :destroy
  has_many :collected_articles, through: :collects, source: :article

  has_many :friend_requests2s, dependent: :destroy
  has_many :pending_friends, through: :friend_requests2s, source: :friend

  has_many :friendship2s, dependent: :destroy
  has_many :friends, through: :friendship2s

  mount_uploader :avatar, AvatarUploader

  ROLE_STATUS = [
    ["Admin", :admin],
    ["Normal", :normal]
  ]

  def admin?
    self.role == "admin"
  end

  def remove_friend(friend)
    friends.destroy(friend)
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])
      sign_in(user, store: false) if user
    end
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendship2s_helper.rb
module Friendship2sHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-hear">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> 
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>     
                <ul class="pull-left text-right nav navbar-nav">
                  <li><%= link_to "Dojo Forum", root_path %></li>
                  <li><%= link_to 'Feeds', feeds_articles_path %></li>
                  <li><%= link_to 'All Post', articles_path %></li>
                  <li><%= link_to 'New Post', new_article_path %> </li>
                </ul>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="pull-right text-right nav navbar-nav">
                <% if current_user %>
                  <li><p class="navbar-text">Hi, <%= current_user.email %>(<% if current_user&.admin? %><%= link_to 'Admin', admin_categories_path %><% end %>)</p></li>
                  <li><%= link_to 'Profile', posted_articles_user_path(current_user), method: :get %></li>
                  <li><%= link_to('Log Out', destroy_user_session_path, method: :delete)%></li>
                <% else %>
                  <li><%= link_to('Register', new_user_registration_path) %></li>
                  <li><%= link_to('Log In', new_user_session_path) %></li>
                <% end %>
                </ul>
              </div>
            </div>
          </nav>
          <% if flash[:notice] %>
            <div class="container col-md-12">
              <div class="row">
                <div class="alert alert-success alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <%= notice %>
                </div>
              </div>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="container col-md-12">
              <div class="row">
               <div class="alert alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <%= alert %>
                </div>
              </div>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_article_list.html.erb
<div class="container_article">
<table class="sortable table table-striped">
  <thead>
    <tr>
      <th width="15%" ><%= sort_link(@q, :comments_count, 'Replilies count', default_order: :desc)%></th>
      <th width="35%">Title</th>
      <th width="30%"><%= sort_link(@q, :comments_created_at, 'Last replied at', default_order: :desc)%></th>
      <th width="9%"><%= sort_link(@q, :views_count, 'View count', default_order: :desc)%></th>
    </tr>
  </thead>
  <tbody>
    <% @article.each do |article|%>
    <% if article.published? %>
      <tr>
        <td><p><%= article.comments_count %></p></td>
        <td><%= article.title %></td>
        <td><%= article.comments.last.created_at.strftime('%Y-%m-%d') if article.comments.last.present? %></td>
        <td><%= link_to '', article_path(article), class: "fas fa-eye"%> <%= article.views_count %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/shared/_category_nav.html.erb
<ul class="nav nav-pills nav-pills-center">
  <li role="presentation">
    <%= link_to "All", root_path %>
  </li>
  <% @categories.each do |category| %>
    <li role="presentation" class="<%= "active" if category == @category %>">
      <%= link_to category.name, category_path(category) %>
    </li>
  <% end %>
</ul>

app/views/shared/_user_collect.html.erb
<% if article.is_collected?(current_user)%>
  <%= link_to 'Uncollect', uncollect_article_path(article), remote: true, method: :post, class: "btn btn-md btn-primary pull-right", id: "uncollect-#{article.id}" %>
<% else %> 
  <%= link_to 'Collect', collect_article_path(article), remote: true, method: :post, class: "btn btn-md btn-primary pull-right",  id: "collect-#{article.id}" %>
<% end %>

app/views/shared/_user_friend.html.erb
<% if current_user.friends.include?(user) %>
  <%= link_to "Remove Friend", friendship2_path(user), method: :delete, class: "btn btn-danger btn-raised" %>
  <% else %>
    <% if current_user.pending_friends.include?(user) || user.pending_friends.include?(current_user) %>
    <button class="btn btn-default disabled">Friend Request Sent</button>
    <% elsif user.friends.include?(current_user) %>
      <h4 class="text-info">You are friends!</h4>
    <% else %>
      <%= link_to 'Add Friend', friend_requests2s_path(friend_id: user.id), method: :post, class: 'btn btn-primary btn-raised' %>
  <% end %>
<% end %>

app/views/shared/_user_nav.html.erb
<div class="col-md-10 col-md-offset-1 user_nav ">
  <div class="page-header">
    <div class="col-md-3 col-sm-4 ">
      <div class="text-center">
        <!-- <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded"> -->
        <%= image_tag @user.avatar, width: "100%", class: "img-responsive img-rounded" if @user.avatar? %>
      </div>
      <div class="pull-left">
        <h2><%= @user.name %></h2>
      </div>
    </div>
    <div class="col-md-9 col-sm-8">
      <div class="user_intro">
        <%= simple_format @user.intro %>
      </div>
      <div class="user_edit">
        <% if @user == current_user %>
          <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-md btn-primary" %>
        <% end %>
        <%unless @user == current_user %>
          <%= render partial: "shared/user_friend", locals: {user: @user} %>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
  <br>
  <div class="col-md-12 user_tab">
    <ul class="nav nav-tabs">
      <li class="<%= active_class(posted_articles_user_path) %>"><%= link_to 'My Post', posted_articles_user_path(@user), method: :get %> </li>
      <li class="<%= active_class(posted_comments_user_path) %>"><%= link_to 'My Comment', posted_comments_user_path(@user), method: :get %></li>
      <% if @user == current_user %>
        <li class="<%= active_class(collected_articles_user_path) %>"><%= link_to 'My Collect', collected_articles_user_path(@user), method: :get %></li>
        <li class="<%= active_class(posted_drafts_user_path) %>"><%= link_to 'My Draft', posted_drafts_user_path(@user), method: :get %></li>
      <% end %>
        <li class="<%= active_class(friends_user_path) %>"><%= link_to 'My Friend', friends_user_path(current_user), method: :get %></li>
    </ul>
  </div>
</div>